// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_pkNAXq6GqZUMX-uyM9dimjHry4JsXFg',
    appId: '1:1028882422117:web:d96e5968b042433360298c',
    messagingSenderId: '1028882422117',
    projectId: 'fir-app-a7673',
    authDomain: 'fir-app-a7673.firebaseapp.com',
    storageBucket: 'fir-app-a7673.appspot.com',
    measurementId: 'G-JBPBCNE8P6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4Uk7XPdWnZiMgM75AQjvohoaY8oSXG7s',
    appId: '1:1028882422117:android:a6377377b8a0283860298c',
    messagingSenderId: '1028882422117',
    projectId: 'fir-app-a7673',
    storageBucket: 'fir-app-a7673.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ8M-pHiKE6esN587VkA8Ah5Iaq0jRN1U',
    appId: '1:1028882422117:ios:b5a71315e839516960298c',
    messagingSenderId: '1028882422117',
    projectId: 'fir-app-a7673',
    storageBucket: 'fir-app-a7673.appspot.com',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ8M-pHiKE6esN587VkA8Ah5Iaq0jRN1U',
    appId: '1:1028882422117:ios:996debd705f945c860298c',
    messagingSenderId: '1028882422117',
    projectId: 'fir-app-a7673',
    storageBucket: 'fir-app-a7673.appspot.com',
    iosBundleId: 'com.example.firebaseApp.RunnerTests',
  );
}
